apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo
  namespace: chandu
  labels:
    app: dotnetdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: dotnetdemo
        image: testacr6666.azurecr.io/dotnetdemo:1.0
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: testacr6666